# KNN implementation on our dataset (100 samples)

In [5]:
import pandas as pd
df=pd.read_excel('dataset.xlsx')
df.head()

G         P  T
0  0.008667  0.018119  0
1  0.164500  0.369489  0
2  0.717500  1.601420  0
3  0.902167  1.973920  0
4  1.086000  2.448440  0

In [6]:
df.keys()

Index(['G', 'P', 'T'], dtype='object')

In [7]:
import numpy as np
array=df.values
array

array([[8.66667e-03, 1.81187e-02, 0.00000e+00],
       [1.64500e-01, 3.69489e-01, 0.00000e+00],
       [7.17500e-01, 1.60142e+00, 0.00000e+00],
       [9.02167e-01, 1.97392e+00, 0.00000e+00],
       [1.08600e+00, 2.44844e+00, 0.00000e+00],
       [9.98833e-01, 2.15653e+00, 0.00000e+00],
       [1.28200e+00, 2.91351e+00, 0.00000e+00],
       [1.76617e+00, 3.95738e+00, 0.00000e+00],
       [2.01067e+00, 4.35130e+00, 0.00000e+00],
       [2.30050e+00, 4.94869e+00, 0.00000e+00],
       [2.40200e+00, 5.29210e+00, 1.00000e+00],
       [3.07767e+00, 6.66302e+00, 1.00000e+00],
       [3.79467e+00, 8.64435e+00, 1.00000e+00],
       [4.15051e+00, 9.45593e+00, 1.00000e+00],
       [4.73148e+00, 1.03360e+01, 1.00000e+00],
       [5.61683e+00, 1.26451e+01, 1.00000e+00],
       [6.61217e+00, 1.50686e+01, 1.00000e+00],
       [7.85417e+00, 1.67875e+01, 1.00000e+00],
       [8.82085e+00, 1.90216e+01, 1.00000e+00],
       [9.58836e+00, 2.01338e+01, 1.00000e+00],
       [1.05410e+01, 2.30706e+01, 2.0000

In [41]:
x=array[:,0:2]
x

array([[8.66667e-03, 1.81187e-02],
       [1.64500e-01, 3.69489e-01],
       [7.17500e-01, 1.60142e+00],
       [9.02167e-01, 1.97392e+00],
       [1.08600e+00, 2.44844e+00],
       [9.98833e-01, 2.15653e+00],
       [1.28200e+00, 2.91351e+00],
       [1.76617e+00, 3.95738e+00],
       [2.01067e+00, 4.35130e+00],
       [2.30050e+00, 4.94869e+00],
       [2.40200e+00, 5.29210e+00],
       [3.07767e+00, 6.66302e+00],
       [3.79467e+00, 8.64435e+00],
       [4.15051e+00, 9.45593e+00],
       [4.73148e+00, 1.03360e+01],
       [5.61683e+00, 1.26451e+01],
       [6.61217e+00, 1.50686e+01],
       [7.85417e+00, 1.67875e+01],
       [8.82085e+00, 1.90216e+01],
       [9.58836e+00, 2.01338e+01],
       [1.05410e+01, 2.30706e+01],
       [1.18705e+01, 2.58331e+01],
       [1.33610e+01, 2.82364e+01],
       [1.48382e+01, 3.37924e+01],
       [1.59688e+01, 3.35944e+01],
       [1.73250e+01, 3.69484e+01],
       [1.85133e+01, 4.07513e+01],
       [1.94707e+01, 4.43170e+01],
       [2.01730e+01,

In [40]:
y=array[:,2]
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [85]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)
x_train.shape

(90, 2)

In [91]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [92]:
y_pred=knn.predict(x_test)

In [93]:
import sklearn.metrics as metrics
z=metrics.accuracy_score(y_test,y_pred)
z

0.9

# Conclusion: Accuracy of 90% with K=1 and a test sample of 10%